### PR TITLE
Add 'Clear icon cache' button for provider

### LINKED ISSUE #213: [BUG] problem in managing channel thumbnails
I have encountered a problem in the cache of the channel icons, if I change the link to the icon via `tvg-logo="my new link"` this is not updated by hypnotix, I have not found a way to clear the cache of the icons downloaded by hypnotix, I have tried to re-add the playlist, but the result doesn't change. If, on the other hand, I change the title, the updated icon appears, but if I put the right one back, this old icon returns.
immagine

### PR DESCRIPTION
**Pull request by qarkai**
Fix #213.

### CODE REVIEW

**Comment by dasaferi** [comment]
Thank you very much @qarkai for creating a pull request to fix the issue I opened.

**Comment by qarkai** [comment]
@dasaferi from https://github.com/linuxmint/hypnotix/graphs/commit-activity I guess we have to wait for another half year before it gets merged.

**Comment by clefebvre** [comment]
Fixed on master. I didn't take the refactoring.

**Comment by qarkai** [comment]
> Fixed on master.

Then you should close #213 manually.

**Comment by dasaferi** [comment]
@qarkai  I tried the Clear icon cache key (hypnotix --> providers --> Clear icon cache button) and nothing happens, if I go to `~/.cache/hypnotix/` the png, jpg, gif, etc. files always remain and aren't deleted. 🤔 i have build package from master of github   [following this guide](https://github.com/linuxmint/hypnotix/issues/19#issuecomment-730355138).

**Comment by qarkai** [comment]
@dasaferi it should delete icons listed in playlist, not all icons from `~/.cache/hypnotix/`.

**Comment by dasaferi** [comment]
> @dasaferi it should delete icons listed in playlist, not all icons from `~/.cache/hypnotix/`.
with freetv the button works, but if I load a local m3u file, the button doesn't work because the icons remain in the providers folder

**Comment by qarkai** [comment]
@dasaferi can you provide this playlist?

**Comment by dasaferi** [comment]
> @dasaferi can you provide this playlist?

I noticed that the problem is not with the local playlistsbut concerns the movies and series category `group-title="VOD ITA" and group-title="SERIES ITA pluto.tv`, the same bug occurs with the free-tv playlist, I downloaded the free-tv playlist customizing it with only the country that interests me and I could not understand why it no longer cleared the icon cache, then I tried the official one and the tv channels icons are cleared while those of movies do not.

**Pull request closed without merging**
