### PR TITLE
Add XTream API

### PR DESCRIPTION
**Pull request by superolmo**
This MR is for supporting Providers with XTream API. I have added a file called xtream.py, but I also added the same file to pypi.org under the name pyxtream. Code will try to load pyxtream, if not available it will use the local file. I will the maintainers of this repo decide whichever way they want to handle it.
I added the suggestion specified in #91 and it should take care or #48 and #116 as well. This does not handle M3U.

### CODE REVIEW

**Comment by superolmo** [comment]
Forgot to mention, I updated all the absolute paths to relative. It made it easier for me to test the software without installing.

**Comment by superolmo** [comment]
Rebased to version 1.7

**Comment by milomak** [comment]
will cloning the repo now include the ability to use xtream api codes?

**Comment by superolmo** [comment]
@milomak please follow the below commands. Probably there is a faster/better way, but for now it works.
```shell
git clone git@github.com:linuxmint/hypnotix.git
git fetch origin pull/148/head:hypnotix/master
git checkout hypnotix/master
```
For my testing I run from the repo root the command:
```shell
python3 usr/lib/hypnotix/hypnotix.py
```

**Comment by milomak** [comment]
$ git clone ***@***.***:linuxmint/hypnotix.git
Cloning into 'hypnotix'...
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of
known hosts.
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by superolmo** [comment]
@milomak  Please open a New Issue. This is just a problem with your git setup, see [Cloning with SSH URLs](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/about-remote-repositories#cloning-with-ssh-urls)

**Comment by milomak** [comment]
tried adding an iptv account that uses xtream codes api. the below were the results

$ python3 usr/lib/hypnotix/hypnotix.py
Loading providers...
XTREAM Loading Channels
Loaded 47 Live Groups in 0.588 seconds
Loaded 5289 Live Streams in 2.649 seconds
'is_adult'
Traceback (most recent call last):
  File "/home/milomak/hypnotix/usr/lib/hypnotix/hypnotix.py", line 1289, in reload
    self.x.load_iptv()
  File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 538, in load_iptv
    new_channel = Channel(
  File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 82, in __init__
    self.is_adult = stream_info['is_adult']
KeyError: 'is_adult'
Couldn't parse provider info:  IPTV:::xtream:::http://iptvlink:2082/:::milomak:::password:::
Loading providers...
XTREAM Loading Channels
Loaded 47 Live Groups in 0.000 seconds
Loaded 5289 Live Streams in 0.000 seconds
'is_adult'
Traceback (most recent call last):
  File "/home/milomak/hypnotix/usr/lib/hypnotix/hypnotix.py", line 1289, in reload
    self.x.load_iptv()
  File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 538, in load_iptv
    new_channel = Channel(
  File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 82, in __init__
    self.is_adult = stream_info['is_adult']
KeyError: 'is_adult'
Couldn't parse provider info:  IPTV:::xtream:::http://iptvlink:2082/:::milomak:::password:::

i am running debian sid so i suspect that plays a part of the issue

**Comment by milomak** [comment]
oaajgpjnedpempjm

this is what i see after waiting more than 10 minutes

**Comment by superolmo** [comment]
> tried adding an iptv account that uses xtream codes api. the below were the results
> 
> $ python3 usr/lib/hypnotix/hypnotix.py
> 
> ```
> Loading providers...
> XTREAM Loading Channels
> Loaded 47 Live Groups in 0.588 seconds
> Loaded 5289 Live Streams in 2.649 seconds
> 'is_adult'
> Traceback (most recent call last):
>   File "/home/milomak/hypnotix/usr/lib/hypnotix/hypnotix.py", line 1289, in reload
>     self.x.load_iptv()
>   File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 538, in load_iptv
>     new_channel = Channel(
>   File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 82, in __init__
>     self.is_adult = stream_info['is_adult']
> KeyError: 'is_adult'
> Couldn't parse provider info:  IPTV:::xtream:::http://iptvlink:2082/:::milomak:::password:::
> Loading providers...
> XTREAM Loading Channels
> Loaded 47 Live Groups in 0.000 seconds
> Loaded 5289 Live Streams in 0.000 seconds
> 'is_adult'
> Traceback (most recent call last):
>   File "/home/milomak/hypnotix/usr/lib/hypnotix/hypnotix.py", line 1289, in reload
>     self.x.load_iptv()
>   File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 538, in load_iptv
>     new_channel = Channel(
>   File "/home/milomak/hypnotix/usr/lib/hypnotix/xtream.py", line 82, in __init__
>     self.is_adult = stream_info['is_adult']
> KeyError: 'is_adult'
> Couldn't parse provider info:  IPTV:::xtream:::http://iptvlink:2082/:::milomak:::password:::
> ```
> 
> i am running debian sid so i suspect that plays a part of the issue

Oh, somehow I knew it. Every xtream implementation has different fields. Your particular implementation does not have the key "is_adult". I am not sure how many more are not defined, but there are few that must be there to work with Hypnotix software. 
I see from the error message that the first 2 files (Live Groups and Live Streams) have been saved under ~/.hypnotix/providers/IPTV-all_streams_Live.json and ~/.hypnotix/providers/IPTV-all_groups_Live.json. Please look for those files and send me a sample of it.

**Comment by milomak** [comment]
those files don't exist

~$ sudo updatedb
[sudo] password for root: 
~$ locate IPTV-all_streams_Live.json
~$ locate IPTV-all_groups_Live.json
~$

**Comment by superolmo** [comment]
@milomak Please pull again from repo and test the new changes.

**Comment by milomak** [comment]
great stuff. working now.

**Comment by milomak** [comment]
one thing i noticed is that it picks up the different categories, but has all the channels in every individual category

**Comment by superolmo** [comment]
I realized the same thing, and it should be fixed now.

**Comment by milomak** [comment]
wonderful work. working like a charm.

**Comment by milomak** [comment]
this work is so great. the other alternative is smarters which is some distance behind in understanding how a desktop app works.

i am so appreciative of your efforts.

**Comment by rht125** [comment]
Can you Please add these android app Live Indian TV feed in your application ..
https://play.google.com/store/apps/details?id=com.straspo.Krik&hl=hi&gl=US
https://play.google.com/store/apps/details?id=com.jio.jioplay.tv&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.jio.media.ondemand&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=in.startv.hotstar.dplus&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.tv.v18.viola&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.sonyliv&hl=en_IN&gl=US
https://play.google.com/store/apps/details?id=com.graymatrix.did&hl=en_IN&gl=US

**Comment by rht125** [comment]
2 more aps
https://play.google.com/store/apps/details?id=tv.accedo.airtel.wynk&hl=en
https://play.google.com/store/apps/details?id=com.vodafone.vodafoneplay&hl=en_IN&gl=US

**Comment by superolmo** [comment]
> Can you Please add these android app Live Indian TV feed in your application ..
> https://play.google.com/store/apps/details?id=com.straspo.Krik&hl=hi&gl=US
> https://play.google.com/store/apps/details?id=com.jio.jioplay.tv&hl=en_IN&gl=US
> https://play.google.com/store/apps/details?id=com.jio.media.ondemand&hl=en_IN&gl=US
> https://play.google.com/store/apps/details?id=in.startv.hotstar.dplus&hl=en_IN&gl=US
> https://play.google.com/store/apps/details?id=com.tv.v18.viola&hl=en_IN&gl=US
> https://play.google.com/store/apps/details?id=com.sonyliv&hl=en_IN&gl=US
> https://play.google.com/store/apps/details?id=com.graymatrix.did&hl=en_IN&gl=US

Not sure what you want to do. This thread is about handling the xtream API in Hypnotix. We don't reverse engineer apps to figure out the source of the video.

**Comment by rht125** [comment]
There are more than 600+ TV channels in India. Hypnotix have only those channels which are already available on youtube.
Like USA have multiple feeds in your software, there is a need of multiple feed from India.

**Comment by superolmo** [comment]
@rht125 Please open an issue at [https://github.com/Free-TV/IPTV](https://github.com/Free-TV/IPTV)

**Comment by clefebvre** [comment]
Hi @superolmo, thanks for this PR, I'm interested in adding support for Xtream API. As it is in master there's no real support, we just mimick M3U through it really.

That said I can't merge your PR, it contains too many unrelated changes.

Here is my feedback:

- pypi shouldn't be involved. If upstream changes occur we can rebase/update the xtream.py hosted here.
- I'm not interested in the relative path. If anything we could use a prefix at build level, but it's not related to Xtream anyway.
- The flag change looks good but is not related to Xtream.
- Do you know if there is a free service we can use to test the Xtream API? Everything we have here uses M3U.

**Comment by superolmo** [comment]
@clefebvre I have removed the pypi reference, the flag name change, and the relative path changes.

**Comment by superolmo** [comment]
Just a word caution, in the past few months, I have been reading lots of negative news about xtream iptv. I do not know of any free IPTV service that use xtream, and it seems that most, if not all, providers are staying away from this protocol in fear of getting sued.

**Comment by milomak** [comment]
so this is now incorporated in the main repo?

**Comment by gromez** [comment]
Just tried Hypnotix 2.1 with XC API support and it seems only some channels are loading in only one group, all other groups are empty.
Debug log looks ok:
```
Loaded 34 Live Groups in 0.000 seconds
Loaded 4551 Live Streams in 0.000 seconds
Loaded 29 VOD Groups in 0.000 seconds
Loaded 5365 VOD Streams in 0.000 seconds
Loaded 31 Series Groups in 0.000 seconds
Loaded 915 Series Streams in 0.000 seconds
```
I will try to debug what's wrong.

**Comment by gromez** [comment]
@superolmo I found the problem, it's here: https://github.com/linuxmint/hypnotix/blob/master/usr/lib/hypnotix/xtream.py#L583
My provider has channel names like this: `|RU| Kinomiks 173`
So, the `alnum` function check the first char `|` and return `False`. Is it possible to change this test?
Thank you

**Comment by superolmo** [comment]
@gromez Yes, it is possible. Would you mind opening an issue? Also, does your provider send subgroups as channels with no stream in it?

**Comment by gromez** [comment]
@superolmo reported here https://github.com/linuxmint/hypnotix/issues/177
And yes I think the subgroups are sent as channels like this `▀▄ SW ▀▄▀▄  DOCS ▄▀▄▀▄▀` so I think that's why you have a check for `alnum` on first char.

**Pull request merged**
