### PR TITLE
Save providers to ~/.cache

### LINKED ISSUE #186: Why .hypnotix folder instead of using linux defaults?
Hey folks,

thanks for this cool application.

I'm just interested why the application uses `.hypnotix` in `HOME`, instead of using the linux defaults, e.g. `.cache`.
IMHO this approach clutters the `HOME` folder, without adding any benefits.

Greetings
Michael

### LINKED ISSUE #201: Use XDG Base Directory Specifications
Currently Hypnotix creates directory with providers list directly in `$HOME` directory. Please move it to correct location according to XDG Base Directory Specifications: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html  
I think `$XDG_CACHE_HOME` (`$HOME/.cache`) should be used, as provider data is updated and not necessary to be backed up.

### PR DESCRIPTION
**Pull request by qarkai**
Fix #186.
Fix #201.

### CODE REVIEW

**Comment by miku86** [comment]
Thanks, this would be a useful PR!

**Comment by qarkai** [comment]
Looks like project is dead. No commits, no PR reviews in 2022.

**Comment by dasaferi** [comment]
@qarkai could you add a button in hypnotix settings to clear icon cache? [#213](https://github.com/linuxmint/hypnotix/issues/213)

**Comment by qarkai** [comment]
@dasaferi maybe I'll add but not in this PR.

**Pull request merged**
